data:
  image: tianon/true
  volumes:
    - /var/lib/postgresql/data
    - /usr/local/taiga/media
    - /usr/local/taiga/static
    - /usr/local/taiga/logs

db:
  image: postgres
  environment:
    POSTGRES_USER: taiga
    POSTGRES_PASSWORD: password
  volumes_from:
    - data
  restart: always
  
taigaback:
  build: taiga-back
  hostname: dev.example.com
  environment:
    SECRET_KEY: examplesecretkey
    EMAIL_USE_TLS: True
    EMAIL_HOST: smtp.gmail.com
    EMAIL_PORT: 587
    EMAIL_HOST_USER: youremail@gmail.com
    EMAIL_HOST_PASSWORD: yourpassword
  links:
    - db:postgres
    - events
    - rabbit
    - redis
  volumes_from:
    - data
  restart: always
  
taigafront:
  build: taiga-front-dist
  hostname: dev.example.com
  links:
    - taigaback
  volumes_from:
    - data
  ports:
    - 0.0.0.0:80:80
  restart: always
  
rabbit:
  image: rabbitmq:3
  hostname: taiga-rabbit

redis:
  image: redis:3

celery:
  image: celery
  links:
    - rabbit

events:
  image: benhutchins/taiga-events
  links:
    - rabbit
